
version: 2

models:
  - name: lower.sql 
    description: "convert all text to lowercase"
    columns:
      - name: title
        description: "interview title"
      - name: question
        description: "interview question"
      - name: answer
        description: "interview answer"

  - name: clean.sql
    description: "remove punctuation and instances of single s"
    columns:
      - name: title
        description: "interview title"
      - name: question
        description: "interview question"
      - name: answer
        description: "interview answer"
